#!/usr/bin/env python3
# Copyright 2026 Feral
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.
"""Regenerate every Feral launcher / notification / onboarding icon from the brand sources.

Feral-owned tool (absent upstream, see docs/FERAL_MAINTENANCE.md §4).

Inputs — tools/feral/brand/
    feral-badge.png   the badge artwork: 480x480, near-black plate, glossy green disc
                      of diameter 416 centred, white glyph on top.
    feral-glyph.svg   the *vector* source of that same glyph (a potrace inverted trace:
                      the whole canvas is filled and the logo is knocked out, so the
                      glyph mask is the negated alpha channel).

The badge's own proportions drive everything:
    disc   = 416/480 of the artwork canvas
    glyph  = 256/416 of the disc            -> GLYPH_OVER_DISC below

Android adaptive icons are two 108dp layers of which the launcher mask only ever shows
the central 72dp viewport.  Putting the disc at DISC_DP = 86dp (the smallest diameter
that still covers a squircle mask, whose corners reach ~85.7dp) means no launcher shape
can ever reveal the artwork's black plate, while keeping ~84% of the sphere's gradient.
The glyph is sized against the *viewport*, not the disc, so what the user sees inside the
mask keeps the badge's own glyph-to-disc ratio.

Usage:  python3 tools/feral/gen-app-icons.py [--check]
        --check  regenerate into a temp dir and diff, without touching the tree.

Requires Pillow and ImageMagick (`magick`) for the SVG rasterisation and webp encoding.
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

REPO = Path(__file__).resolve().parents[2]
BRAND = REPO / "tools" / "feral" / "brand"
BADGE = BRAND / "feral-badge.png"
GLYPH_SVG = BRAND / "feral-glyph.svg"

# ---------------------------------------------------------------- geometry --
LAYER_DP = 108.0          # adaptive-icon layer
VIEWPORT_DP = 72.0        # what any launcher mask can show
DISC_DP = 86.0            # sphere diameter on the layer (>= 85.7 covers a squircle)
GLYPH_OVER_DISC = 256.0 / 416.0   # 0.6154 - the badge's own ratio
GLYPH_DP = VIEWPORT_DP * GLYPH_OVER_DISC          # 44.31dp

DENSITIES = [("mdpi", 1.0), ("hdpi", 1.5), ("xhdpi", 2.0), ("xxhdpi", 3.0), ("xxxhdpi", 4.0)]
LEGACY_DP = 48.0          # pre-API-26 launcher icon (minSdk is 24)
NOTIF_DP = 24.0           # status-bar "small" icon
PLAYSTORE_PX = 512
LOGIN_LOGO_PX = 640       # 160dp at xxxhdpi (4x); kept in drawable-xxhdpi like
                          # feral_logo_black.png, so Android downscales rather than
                          # upscaling it on 4x screens

PLATE_RGB = (1, 3, 2)     # the artwork's near-black plate

APPICON = REPO / "appicon" / "element" / "src"
APPRES = REPO / "app" / "src" / "main" / "res"
LOGINRES = REPO / "features" / "login" / "impl" / "src" / "main" / "res"

LICENSE_XML = """<?xml version="1.0" encoding="utf-8"?><!--
  ~ Copyright (c) 2026 Element Creations Ltd.
  ~ Copyright 2023 New Vector Ltd.
  ~
  ~ SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
  ~ Please see LICENSE files in the repository root for full details.
  ~ Modified by Feral: adaptive-icon background = the Feral badge's sphere gradient.
  ~ Generated by tools/feral/gen-app-icons.py - do not hand-edit.
  -->
"""


def run(*cmd: str) -> None:
    subprocess.run(cmd, check=True, capture_output=True)


# ------------------------------------------------------------------ sources --
def load_glyph_mask(size: int) -> Image.Image:
    """Tight white-on-black mask of the logo, rasterised from the vector at `size`."""
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "m.png"
        run("magick", "-background", "none", "-density", "600", str(GLYPH_SVG),
            "-resize", "2048x2048", "-alpha", "extract", "-negate", str(out))
        m = Image.open(out).convert("L")
    box = m.point(lambda v: 255 if v > 127 else 0).getbbox()
    return m.crop(box).resize((size, size), Image.LANCZOS)


def build_plate() -> Image.Image:
    """The badge with its glyph removed - a clean sphere on the near-black plate.

    The background is left/right symmetric about the disc centre, so most of the glyph
    can be filled from its own mirror image; the rest is closed by normalized-convolution
    diffusion.  Everything reconstructed here ends up underneath the glyph again anyway.
    """
    badge = Image.open(BADGE).convert("RGB")
    w, h = badge.size
    cx = cy = (w - 1) / 2.0

    mask = Image.new("L", (w, h), 0)
    # the artwork's glyph occupies a 256px box centred on the disc
    gsize = int(round(w * (416.0 / 480.0) * GLYPH_OVER_DISC))
    mask.paste(load_glyph_mask(gsize), (int(round(cx - gsize / 2)), int(round(cy - gsize / 2))))
    mask = mask.filter(ImageFilter.MaxFilter(11)).point(lambda v: 255 if v > 8 else 0)

    src, mk = badge.load(), mask.load()
    known = [[mk[x, y] == 0 for x in range(w)] for y in range(h)]

    img = Image.new("RGB", (w, h))
    kn = Image.new("L", (w, h), 0)
    ip, kp = img.load(), kn.load()
    for y in range(h):
        for x in range(w):
            if known[y][x]:
                ip[x, y] = src[x, y]
                kp[x, y] = 255
            else:                                        # pass 1: mirror fill
                mx = int(round(2 * cx - x))
                if 0 <= mx < w and known[y][mx]:
                    ip[x, y] = src[mx, y]
                    kp[x, y] = 255

    for _ in range(90):                                  # pass 2: diffusion
        bi, bk = img.filter(ImageFilter.GaussianBlur(6)), kn.filter(ImageFilter.GaussianBlur(6))
        bip, bkp = bi.load(), bk.load()
        changed = 0
        for y in range(h):
            for x in range(w):
                if kp[x, y] == 0 and bkp[x, y] > 3:
                    wgt = bkp[x, y] / 255.0
                    ip[x, y] = tuple(min(255, int(round(c / wgt))) for c in bip[x, y])
                    kp[x, y] = 255
                    changed += 1
        if not changed:
            break

    smooth = img.filter(ImageFilter.GaussianBlur(2.5))
    out = Image.new("RGB", (w, h))
    op, sp, om = out.load(), smooth.load(), mask.load()
    for y in range(h):
        for x in range(w):
            op[x, y] = sp[x, y] if om[x, y] else src[x, y]
    return out


# ------------------------------------------------------------- composition --
def _circle_alpha(size: int) -> Image.Image:
    ss = 4
    m = Image.new("L", (size * ss, size * ss), 0)
    ImageDraw.Draw(m).ellipse([0, 0, size * ss - 1, size * ss - 1], fill=255)
    return m.resize((size, size), Image.LANCZOS)


def disc_layer(plate: Image.Image, canvas: int, disc_px: float, bleed: bool) -> Image.Image:
    """The sphere at `disc_px` diameter, centred on a `canvas` square.

    Outside the disc: the plate colour, or - when `bleed` - the disc's own rim colour
    smeared radially outwards so that no mask shape can expose a hard edge.
    """
    d = int(round(disc_px))
    scale = plate.size[0] / (plate.size[0] * 416.0 / 480.0)   # canvas/disc of the artwork
    full = int(round(d * scale))
    sphere = plate.resize((full, full), Image.LANCZOS)
    out = Image.new("RGB", (canvas, canvas), PLATE_RGB)
    off = (canvas - full) // 2
    ring = Image.new("L", (full, full), 0)
    r = d / 2.0
    c = full / 2.0
    ss = 4
    big = Image.new("L", (full * ss, full * ss), 0)
    ImageDraw.Draw(big).ellipse([(c - r) * ss, (c - r) * ss, (c + r) * ss, (c + r) * ss], fill=255)
    ring = big.resize((full, full), Image.LANCZOS)
    out.paste(sphere, (off, off), ring)
    if not bleed or disc_px >= canvas:
        return out
    sp, op = sphere.load(), out.load()
    ccx = ccy = canvas / 2.0
    for y in range(canvas):
        for x in range(canvas):
            dx, dy = x - ccx, y - ccy
            rr = math.hypot(dx, dy)
            if rr > r - 1.0 and rr > 0:
                k = (r - 1.2) / rr
                sx = max(0, min(full - 1, int(round(c + dx * k))))
                sy = max(0, min(full - 1, int(round(c + dy * k))))
                op[x, y] = sp[sx, sy]
    return out.filter(ImageFilter.GaussianBlur(canvas / 220.0))


def glyph_layer(canvas: int, glyph_px: int) -> Image.Image:
    a = Image.new("L", (canvas, canvas), 0)
    a.paste(load_glyph_mask(glyph_px), ((canvas - glyph_px) // 2, (canvas - glyph_px) // 2))
    fg = Image.new("RGBA", (canvas, canvas), (255, 255, 255, 0))
    fg.paste((255, 255, 255, 255), (0, 0), a)
    return fg


def mask_alpha(canvas: int, kind: str, side: float) -> Image.Image:
    ss = 4
    S = canvas * ss
    v = side * ss
    off = (S - v) / 2.0
    m = Image.new("L", (S, S), 0)
    dr = ImageDraw.Draw(m)
    if kind == "circle":
        dr.ellipse([off, off, off + v, off + v], fill=255)
    elif kind == "rounded":
        dr.rounded_rectangle([off, off, off + v, off + v], radius=v * 0.28, fill=255)
    elif kind == "square":
        dr.rectangle([off, off, off + v, off + v], fill=255)
    return m.resize((canvas, canvas), Image.LANCZOS)


def save_png(im: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    im.save(path, "PNG", optimize=True)


def save_webp(im: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    im.save(path, "WEBP", lossless=True, quality=100, method=6)


# ------------------------------------------------------------------- vector --
def background_vector(plate: Image.Image, darken: float) -> str:
    """<vector> whose vertical multi-stop gradient reproduces the sphere's shading.

    Sampled down the (now glyph-free) centre column of the plate across the disc; the
    sphere's faint radial rim-light is dropped, which is invisible at icon size and buys
    a 1 kB resolution-independent drawable instead of ten raster files.
    """
    px = plate.load()
    w = plate.size[0]
    cx = (w - 1) / 2.0
    r = w * (416.0 / 480.0) / 2.0
    n = 13
    stops = []
    for i in range(n):
        t = i / (n - 1)
        y = max(0, min(w - 1, int(round(cx - r + t * 2 * r))))
        c = tuple(max(0, min(255, int(round(v * darken)))) for v in px[int(cx), y])
        stops.append((t, "#FF%02X%02X%02X" % c))
    y0 = (LAYER_DP - DISC_DP) / 2.0
    y1 = LAYER_DP - y0
    items = "\n".join(
        '                <item android:offset="%.4f" android:color="%s" />' % (t, c)
        for t, c in stops
    )
    return (
        LICENSE_XML
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        '    <path\n'
        '        android:fillType="evenOdd"\n'
        '        android:pathData="m0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        '                android:startX="54" android:startY="%.1f"\n'
        '                android:endX="54" android:endY="%.1f">\n' % (y0, y1)
        + items
        + "\n            </gradient>\n"
        "        </aapt:attr>\n"
        "    </path>\n"
        "</vector>\n"
    )


# -------------------------------------------------------------------- build --
def generate(root: Path) -> list[Path]:
    plate = build_plate()
    written: list[Path] = []

    def out(rel: str) -> Path:
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        written.append(p)
        return p

    for name, scale in DENSITIES:
        layer = int(round(LAYER_DP * scale))
        gpx = int(round(GLYPH_DP * scale))
        fg = glyph_layer(layer, gpx)
        save_webp(fg, out(f"appicon/element/src/main/res/mipmap-{name}/ic_launcher_foreground.webp"))
        save_webp(fg, out(f"appicon/element/src/main/res/mipmap-{name}/ic_launcher_monochrome.webp"))

        # legacy pre-API-26 icons: the same composition, cropped to the mask viewport
        composed = disc_layer(plate, layer, layer * DISC_DP / LAYER_DP, True).convert("RGBA")
        composed.alpha_composite(fg)
        legacy = int(round(LEGACY_DP * scale))
        vp = layer * VIEWPORT_DP / LAYER_DP
        for kind, fname in (("rounded", "ic_launcher.webp"), ("circle", "ic_launcher_round.webp")):
            masked = Image.new("RGBA", (layer, layer), (0, 0, 0, 0))
            masked.paste(composed, (0, 0), mask_alpha(layer, kind, vp))
            crop = int(round((layer - vp) / 2))
            tile = masked.crop((crop, crop, layer - crop, layer - crop)).resize(
                (legacy, legacy), Image.LANCZOS)
            save_webp(tile, out(f"appicon/element/src/main/res/mipmap-{name}/{fname}"))

        # status-bar small icon: the glyph alone, content-cropped, white on transparent
        npx = int(round(NOTIF_DP * scale))
        save_png(glyph_layer(npx, npx), out(f"app/src/main/res/drawable-{name}/ic_notification_feral.png"))

    for build_type, darken in (("release", 1.0), ("nightly", 0.68)):
        p = out(f"appicon/element/src/{build_type}/res/drawable/ic_launcher_background.xml")
        p.write_text(background_vector(plate, darken), encoding="utf-8")

    # Play Store / standalone square asset: the badge exactly as drawn, opaque.
    ps = disc_layer(plate, PLAYSTORE_PX, PLAYSTORE_PX * 416.0 / 480.0, False).convert("RGBA")
    ps.alpha_composite(glyph_layer(PLAYSTORE_PX, int(round(PLAYSTORE_PX * 416.0 / 480.0 * GLYPH_OVER_DISC))))
    save_png(ps.convert("RGB"), out("appicon/element/src/main/ic_launcher-playstore.png"))

    # Onboarding badge: the coin with no plate, so it floats on the dark login gradient.
    lg = disc_layer(plate, LOGIN_LOGO_PX, LOGIN_LOGO_PX, False).convert("RGBA")
    lg.putalpha(_circle_alpha(LOGIN_LOGO_PX))
    lg.alpha_composite(glyph_layer(LOGIN_LOGO_PX, int(round(LOGIN_LOGO_PX * GLYPH_OVER_DISC))))
    save_png(lg, out("features/login/impl/src/main/res/drawable-xxhdpi/feral_badge.png"))

    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="generate into a temp dir and report differences instead of writing")
    args = ap.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            for p in generate(tmp):
                rel = p.relative_to(tmp)
                cur = REPO / rel
                if not cur.exists():
                    print(f"MISSING  {rel}")
                elif cur.read_bytes() != p.read_bytes():
                    print(f"DIFFERS  {rel}")
        return 0

    for p in generate(REPO):
        print(f"wrote {p.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
