/*
 * Copyright 2025 Feral
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
 * Please see LICENSE files in the repository root for full details.
 */

package io.element.android.features.login.impl.screens.onboarding

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp

/**
 * The Feral badge — the app icon itself — on the dark onboarding gradient.
 *
 * The disc carries its own colour, so it is drawn untinted; the artwork already has
 * transparent corners, which is why it needs no container of its own.
 * Regenerated by tools/feral/gen-app-icons.py from tools/feral/brand/.
 */
@Composable
fun FeralLogo(
    modifier: Modifier = Modifier
) {
    Image(
        modifier = modifier.size(160.dp),
        painter = painterResource(id = io.element.android.features.login.impl.R.drawable.feral_badge),
        contentDescription = null,
        contentScale = ContentScale.Fit,
    )
}
